#pragma config(Sensor, dgtl1,  ForkTopLimit,   sensorTouch)
#pragma config(Sensor, dgtl4,  ForkBottomLimit, sensorTouch)
#pragma config(Sensor, dgtl9,  sonarSensor,    sensorSONAR_inch)
#pragma config(Motor,  port2,           TriggerCam,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           ForkLiftDrive, tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           ForkLiftBrake, tmotorServoStandard, openLoop)
#pragma config(Motor,  port6,           ForkLiftTilt,  tmotorServoStandard, openLoop)
#pragma config(Motor,  port8,           leftMotor,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port9,           rightMotor,    tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Code automatically generated by 'ROBOTC' configuration wizard

#define DB_THRESH 7
//Variables

task main()
{
	while(1 == 1) // A while loops helps the user maintain smooth control of the robot.
	{
		/*----------------------------------------------------------------------------------------------------*\
		|*                                    - Single Joystick Control -                                     *|
		|*                                      ROBOTC on VEX 2.0 Cortex                                      *|
		|*                                                                                                    *|
		|*  This program uses a single joystick, either right or left (this is configurable below) to drive   *|
		|*  the robot. Denton ACES uses the leftMotor configuration for 2017 BEST Crossfire.  					    	*|
		|*																																																		*|
		|*	The sample code has also been adjusted to include a deadband to limit motor 											*|
		|*	whining during operation. 																																				*|
		|*                                                                                                    *|
		|*                                        ROBOT CONFIGURATION                                         *|
		|*    NOTES:                                                                                          *|
		|*    1)  Ch1 is the X axis and Ch2 is the Y axis for the RIGHT joystick.                             *|
		|*    2)  Ch3 is the Y axis and Ch4 is the X axis for the LEFT joystick.                              *|
		|*                                                                                                    *|
		|*    MOTORS & SENSORS:                                                                               *|
		|*    [I/O Port]              [Name]              [Type]              [Description]                   *|
		|*    Motor - Port 9          rightMotor           VEX Motor           Right motor                    *|
		|*    Motor - Port 8          leftMotor            VEX Motor           Left motor                     *|
		\*----------------------------------------------------------------------------------------------------*/


		if (abs((vexRT[Ch3] + vexRT[Ch4])/2) >= DB_THRESH )
		{
			motor[leftMotor]  = (vexRT[Ch3] + vexRT[Ch4])/2;  //(y + x)/2
		}
		else
		{
			motor[leftMotor]  = 0;
		}

		if (abs((vexRT[Ch3] - vexRT[Ch4])/2) >= DB_THRESH)
		{
			motor[rightMotor] = (vexRT[Ch3] - vexRT[Ch4])/2;  //(y - x)/2
		}
		else
		{
			motor[rightMotor] = 0;
		}

		/*----------------------------------------------------------------------------------------------------*\
		|*                                    - Trigger Mechanism -                                     			*|
		|*                                  ROBOTC on VEX 2.0 Cortex         			                            *|
		|*                                                                                                    *|
		|*  This program turns on the motor that rotates the cam causing the trigger to shoot a golf ball.    *|
		|*                                                                                                    *|
		\*----------------------------------------------------------------------------------------------------*/

		if (vexRT[Btn5U] == 1)							//If Btn 5U is pressed **changed to left hand side
																				//== equality operator
		{
			motor[TriggerCam] = -127;					//Trigger Cam rotates at full speed in the positive direction
		}
		else
		{
			motor[TriggerCam] = 0;						//If Btn 5U is not pressed, the trigger cam motor is stopped
																				//= assignment operator
		}

		/*----------------------------------------------------------------------------------------------------*\
		|*                                    - Forklift Mechanism -                                     			*|
		|*                                  ROBOTC on VEX 2.0 Cortex         			                            *|
		|* The forklift is a rack and pinion mechanism. The nested control structures allow for a limit 		  *|
		|* switch that ensures the rack does not travel outside of bounds and fall off the mechanism. This 		*|
		|* would prevent it from functioning without being fixed.																							*|
		|* 																																																		*|
		|* The last version of this code had the fork lift tilt as an automatic motion, tilting while moving,	*|
		|* and untilting while not moving. After testing and collaborating with the build team and robot 			*|
		|* driver, it was determined that we set the tilt mechanism seperately so that the driver would have 	*|
		|* more direct control.																																								*|
		\*----------------------------------------------------------------------------------------------------*/

		if (vexRT[Btn8U] == 1)  						//When Button 8-Up is pressed
		{
			if (SensorValue[dgtl1] == 1) 			//Check if the Forklift is at its top limit.
			{
				motor[ForkLiftDrive] = 0; 			//Motor turns off
			}
			else
			{
				motor[ForkLiftDrive] = 127; 		//Drive forklift motor up
			}
		}
		else if (vexRT[Btn8D] == 1) 				//When Button 8-Down is pressed
		{
			if (SensorValue[dgtl4] == 1 ) 		//Check if the Forklift is at the bottom limit.
			{
				motor[ForkLiftDrive] = 0; 			//Motor turns off
			}
			else
			{
				motor[ForkLiftDrive] = -127; 		//Drive forklift motor down
			}
		}
		else																//If neither Button 8-Up or 8-Down is pressed
		{
			motor[ForkLiftDrive] = 0; 				//Drive motor is stopped.
		}

		if (vexRT[Btn6U] == 1)							//If button 6U is pressed,
		{
			motor[ForkLiftTilt] = 127;				//Untilt
		}
		else
		{
			motor[ForkLiftTilt] = -100;				//Tilt (testing)
		}
	}


		/*----------------------------------------------------------------------------------------------------*\
		|*                                 - Forward until Close Proximity -                                  *|
		|*                                      ROBOTC on VEX 2.0 CORTEX                                      *|
		|*                                                                                                    *|
		|*  This program instructs the robot to drive forward at half speed until the Ultrasonic Sensor       *|
		|*  detects an obstruction within 20 inches of it.                                                    *|                                      *|
		|*                                                                                                    *|
		|*                                        ROBOT CONFIGURATION                                         *|
		|*    NOTES:                                                                                          *|
		|*    1)  Reversing 'rightMotor' (port 2) in the "Motors and Sensors Setup" is needed with the        *|
		|*        "Squarebot" mode, but may not be needed for all robot configurations.                       *|
		|*    2)  The Ultrasonic Sensor returns a value of '-1' when it is out of range from the nearest      *|
		|*        object.  The range is from 0 to 255 inches, so make sure that the robot is within this      *|
		|*        range or it may never run.                                                                  *|
		|*                                                                                                    *|
		|*    MOTORS & SENSORS:                                                                               *|
		|*    [I/O Port]         		[Name]              [Type]                [Description]                   *|
		|*    Motor   - Port 9    	rightMotor          VEX 3-wire module     Right side motor                *|
		|*    Motor   - Port 8    	leftMotor           VEX 3-wire module     Left side motor                 *|
		|*    Digital - Port 9,10 	sonarSensor         VEX Sonar Sensor      Front mounted, facing forward   *|
		\*-----------------------------------------------------------------------------------------------4246-*/

	if (SensorValue(sonarSensor) > 20  || SensorValue(sonarSensor) == -1)		//Loop while robot's Ultrasonic sensor is further than 20 inches away from an object
	{                                                                       //|| (or) it is '-1'.  (-1 is the value returned when nothing is in it's visable range)
		motor[rightMotor] = 127;			//Motor on port9 is run at full (127) power forward
		motor[leftMotor]  = 127;			//Motor on port8 is run at full (127) power forward
		}
		else
		{
			motor[rightMotor] = 0;			//Motor on port9 stops
			motor[leftMotor]  = 0;			//Motor on port8 stops
		}
	}

//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++




//I dont know whether this will change the code but this is a test and it can be rejected from the real code
